"""agent-chokepoint decision engine — the PDP (policy decision point).

Pure library: tool call in, ``allow | block | ask`` plus the rule id that
fired, out. No I/O, no network, no state. Importable standalone — the policy
loader and every enforcement point depend on this package; this package
depends only on the standard library.
"""

from .decide import decide
from .listing import (
    DIGEST_PREFIX,
    UndigestibleDefinition,
    decide_listing,
    tool_definition_digest,
)
from .model import (
    DEFAULT_RULE_ID,
    LIMIT_RULE_PREFIX,
    LISTING_APPROVED_RULE_ID,
    LISTING_DRIFT_RULE_ID,
    LISTING_MIDRUN_RULE_ID,
    LISTING_OWASP,
    LISTING_RULE_PREFIX,
    LISTING_UNPINNED_RULE_ID,
    TAINT_EGRESS_RULE_ID,
    TAINT_NEW_DOMAIN_RULE_ID,
    TAINT_RULE_PREFIX,
    TAINT_SECRET_RULE_ID,
    Decision,
    Defaults,
    EgressMode,
    HiddenContext,
    Limits,
    Policy,
    Rule,
    RunState,
    Taint,
    ToolCall,
    ToolDefinition,
    ToolListing,
    ToolListingPolicy,
    Verdict,
)
from .predicates import (
    ARG_MATCHERS,
    HIDDEN_CONTEXT_MIN_SEGMENT_CHARS,
    INVISIBLE_CHARACTER_CLASSES,
    PREDICATES,
    contains_hidden_context,
    contains_sensitive,
    hidden_context_segments,
    normalized_for_comparison,
)

__all__ = [
    "ARG_MATCHERS",
    "HIDDEN_CONTEXT_MIN_SEGMENT_CHARS",
    "HiddenContext",
    "contains_hidden_context",
    "contains_sensitive",
    "hidden_context_segments",
    "normalized_for_comparison",
    "DEFAULT_RULE_ID",
    "DIGEST_PREFIX",
    "Decision",
    "Defaults",
    "EgressMode",
    "INVISIBLE_CHARACTER_CLASSES",
    "LIMIT_RULE_PREFIX",
    "LISTING_APPROVED_RULE_ID",
    "LISTING_DRIFT_RULE_ID",
    "LISTING_MIDRUN_RULE_ID",
    "LISTING_OWASP",
    "LISTING_RULE_PREFIX",
    "LISTING_UNPINNED_RULE_ID",
    "Limits",
    "PREDICATES",
    "Policy",
    "Rule",
    "RunState",
    "TAINT_EGRESS_RULE_ID",
    "TAINT_NEW_DOMAIN_RULE_ID",
    "TAINT_RULE_PREFIX",
    "TAINT_SECRET_RULE_ID",
    "Taint",
    "ToolCall",
    "ToolDefinition",
    "ToolListing",
    "ToolListingPolicy",
    "UndigestibleDefinition",
    "Verdict",
    "decide",
    "decide_listing",
    "tool_definition_digest",
]
