"""Decision events (JSONL) -> SQL INSERTs on stdout, for the dashboard stack.

    python3 telemetry/dashboard/load_events.py telemetry/samples/*.jsonl \
      | docker compose -f telemetry/dashboard/docker-compose.yml \
          exec -T postgres psql -q -U chokepoint -d chokepoint

Reads the same artifact a deployed gateway writes — `--log-file`'s JSONL, one
event per line (D-024) — and emits INSERTs against the table `schema.sql`
defines. Point it at a pod's `/sandbox/decisions.jsonl` and the dashboard
renders production traffic; the committed samples are only the default corpus.

Standard library only, and no database driver: this prints SQL. A driver would
be a dependency the project does not otherwise need, and text on stdout is
inspectable before it is executed, which matters more here than convenience.

Quoting: literals are single-quoted with `''` doubling, which is the whole of
the escaping needed while `standard_conforming_strings` is on (the Postgres
default since 9.1, and asserted below rather than assumed — the loader emits a
`SET` for it, so a server configured otherwise fails loudly instead of
mangling a backslash inside a JSON argument).

Unknown keys are dropped with a warning on stderr rather than silently: an
event carrying a field this table does not have means the schema moved and the
dashboard is about to under-report. Events missing `ts`, `agent_id` or `method`
are refused outright — the table declares them NOT NULL and a row without them
is not one of these events.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Exactly the columns in schema.sql, which are exactly the fields in
# ../event-schema.json. Order is the INSERT's column order.
COLUMNS = (
    "ts",
    "agent_id",
    "run_id",
    "server",
    "method",
    "tool",
    "arguments",
    "verdict",
    "rule_id",
    "owasp",
    "reason",
    "decision_ms",
    "action",
)
REQUIRED = ("ts", "agent_id", "method")


def literal(value: object) -> str:
    """One SQL literal. JSON-valued fields become their JSON text."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):  # before the int branch: bool is an int
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (dict, list)):
        value = json.dumps(value, sort_keys=True)
    return "'" + str(value).replace("'", "''") + "'"


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__, file=sys.stderr)
        return 2

    rows = 0
    skipped = 0
    out = [
        "-- generated by telemetry/dashboard/load_events.py",
        "SET standard_conforming_strings = on;",
        "BEGIN;",
    ]
    for name in argv:
        path = Path(name)
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError as exc:
                print(f"{path}:{lineno}: not JSON, skipped ({exc})", file=sys.stderr)
                skipped += 1
                continue
            if not isinstance(event, dict) or any(key not in event for key in REQUIRED):
                print(f"{path}:{lineno}: missing one of {REQUIRED}, skipped", file=sys.stderr)
                skipped += 1
                continue
            unknown = set(event) - set(COLUMNS)
            if unknown:
                print(
                    f"{path}:{lineno}: event carries {sorted(unknown)}, which this table has no "
                    "column for - the schema has moved and the dashboard will under-report",
                    file=sys.stderr,
                )
            values = ", ".join(literal(event.get(column)) for column in COLUMNS)
            out.append(f"INSERT INTO events ({', '.join(COLUMNS)}) VALUES ({values});")
            rows += 1
    out.append("COMMIT;")
    print("\n".join(out))
    print(f"{rows} event(s) -> INSERT, {skipped} skipped", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
